### ISSUE TITLE
Any arxiv paper for detailed explanation of this dataset as well as evaluation methods?

### ISSUE THREAD

**Issue by zhimin-z** [NTDXYG/open-eval#1]
Such as the provenance of this dataset and how we should evaluate our models with it. Thanks in advance!

**Comment by NTDXYG** [comment]
The paper will be posted to arxiv shortly and is still being revised.

**Comment by NTDXYG** [comment]
> Such as the provenance of this dataset and how we should evaluate our models with it. Thanks in advance!

The paper will be posted to arxiv shortly and is still being revised.

**Comment by NTDXYG** [comment]
> Such as the provenance of this dataset and how we should evaluate our models with it. Thanks in advance!

https://arxiv.org/abs/2312.05562
